config/routes.rb
Rails.application.routes.draw do
    root 'visitors#index'
    get 'search' => 'visitors#search'

    resources :courses, only: [:show]

    devise_for :users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :courses

    validates_presence_of :name
    validates_uniqueness_of :name
end

app/models/course.rb
class Course < ApplicationRecord
    belongs_to :category
    counter_culture :category

    belongs_to :instructor

    validates_presence_of :name, :category, :instructor

    def self.search(params)
        where("name LIKE ?", "%#{params}%")
    end

    def self.search_by_category(category_id)
        where(:category => category_id)
    end

    scope :confirmed, -> { where(:confirmed => 1) }
    scope :unconfirmed, -> { where(:confirmed => 0) }

    default_scope -> { order(:id => :desc) }
end

app/models/instructor.rb
class Instructor < ApplicationRecord
    has_many :courses

    validates_presence_of :name
    validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable,
        :recoverable, :rememberable, :trackable, :validatable

    validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    private

    # Overwriting the sign_out redirect path method
    def after_sign_out_path_for(resource_or_scope)
        root_path
    end
end

app/controllers/categories_controller.rb
class CategoriesController < InheritedResources::Base

    private

    def category_params
        params.require(:category).permit()
    end
end

app/controllers/courses_controller.rb
class CoursesController < InheritedResources::Base

    private

    def course_params
        params.require(:course).permit()
    end
end

app/controllers/instructors_controller.rb
class InstructorsController < InheritedResources::Base

    private

    def instructor_params
        params.require(:instructor).permit()
    end
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base

    private

    def user_params
        params.require(:user).permit()
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
    def index
        @categories = Category.where('courses_count > ?', 0)
        @courses = Course.confirmed

        if params[:category_id]
            @courses = @courses.search_by_category(params[:category_id])
        end

        @courses = @courses.paginate(:page => params[:page], per_page: 3)
    end

    def search
        if params[:search]
            @courses = Course.confirmed.search(params[:search]).paginate(:page => params[:page], per_page: 6)
            @search_text = params[:search]
        else
            redirect_to :action => :index
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/courses/_form.html.erb
<%= form_for(course) do |f| %>
    <% if course.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

            <ul>
                <% course.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div class="field">
        <%= f.label :description %>
        <%= f.text_area :description %>
    </div>

    <div class="field">
        <%= f.label :prerequisites %>
        <%= f.text_area :prerequisites %>
    </div>

    <div class="field">
        <%= f.label :content %>
        <%= f.text_area :content %>
    </div>

    <div class="field">
        <%= f.label :place %>
        <%= f.text_field :place %>
    </div>

    <div class="field">
        <%= f.label :start %>
        <%= f.date_select :start %>
    </div>

    <div class="field">
        <%= f.label :time %>
        <%= f.text_field :time %>
    </div>

    <div class="field">
        <%= f.label :confirmed %>
        <%= f.check_box :confirmed %>
    </div>

    <div class="field">
        <%= f.label :category_id %>
        <%= f.text_field :category_id %>
    </div>

    <div class="field">
        <%= f.label :instructor_id %>
        <%= f.text_field :instructor_id %>
    </div>

    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<table>
    <thead>
    <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Prerequisites</th>
        <th>Content</th>
        <th>Place</th>
        <th>Start</th>
        <th>Time</th>
        <th>Confirmed</th>
        <th>Category</th>
        <th>Instructor</th>
        <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @courses.each do |course| %>
        <tr>
            <td><%= course.name %></td>
            <td><%= course.description %></td>
            <td><%= course.prerequisites %></td>
            <td><%= course.content %></td>
            <td><%= course.place %></td>
            <td><%= course.start %></td>
            <td><%= course.time %></td>
            <td><%= course.confirmed %></td>
            <td><%= course.category %></td>
            <td><%= course.instructor %></td>
            <td><%= link_to 'Show', course %></td>
            <td><%= link_to 'Edit', edit_course_path(course) %></td>
            <td><%= link_to 'Destroy', course, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
    <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= @course.name %></title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="/css/bootstrap.css">
    <link rel="stylesheet" href="/css/courses.css">
    <%= stylesheet_link_tag 'courses', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <nav class="navbar navbar-default" style="min-height:auto">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active"></li>
                    <a class="navbar-brand" href="/"><img src="/img/logo.png" width="200px"></a>
                </ul>

                <%= form_tag(search_path, method: 'get', class: "navbar-form navbar-right", id: "search-form", enforce_utf8: false) do %>
                    <div class="form-group">
                        <%= text_field_tag :search, params[:search], {class: 'form-control', placeholder: 'Search Courses'} %>
                    </div>
                    <button type="submit" class="btn btn-default">
                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span> Search
                    </button>

                    <a type="button" class="btn btn-success" href="/admin/login">
                        <% if user_signed_in? %>
                            Admin Panel
                        <% else %>
                            Login
                        <% end %>
                    </a>
                <% end %>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
    <br>

    <div class="container">
        <div class="row" style="min-height: 40em">
            <div class="col-md-4">
                <div class="thumbnail">
                    <% if @course.image_url and @course.image_url != '' %>
                        <img src="<%= @course.image_url %>" alt="Course Image">
                    <% else %>
                        <img src="/img/course-square.png" alt="Default Course Image">
                    <% end %>

                    <div align="center" class="caption">
                        <h3><%= @course.name %></h3>
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div role="tabpanel">
                    <ul class="nav nav-tabs" role="tablist">
                        <li class="active"><a href="#home1" data-toggle="tab" role="tab">About</a></li>
                        <li><a href="#paneTwo1" data-toggle="tab" role="tab">Instructor</a></li>
                        <li><a href="#paneThree1" data-toggle="tab" role="tab">Sessions</a></li>
                    </ul>

                    <br>

                    <div id="tabContent1" class="tab-content">
                        <div class="tab-pane fade in active" id="home1">
                            <% if @course.description and @course.description != '' %>
                                <p>
                                    <strong>Description</strong><br>
                                    <span class="preserve-whitespace"><%= @course.description %></span>
                                </p>

                                <hr>
                            <% end %>

                            <% if @course.prerequisites and @course.prerequisites != '' %>
                                <p>
                                    <strong>Prerequisites</strong><br>
                                    <span class="preserve-whitespace"><%= @course.prerequisites %></span>
                                </p>

                                <hr>
                            <% end %>

                            <% if @course.content and @course.content != '' %>
                                <p>
                                    <strong>Content</strong><br>
                                    <span class="preserve-whitespace"><%= @course.content %></span>
                                </p>

                                <hr>
                            <% end %>

                            <% if @course.member_fees and @course.non_member_fees %>
                                <strong>Member Fees</strong><br>
                                <%= @course.member_fees %> EGP<br>
                                <strong>Non member Fees</strong><br>
                                <%= @course.non_member_fees %> EGP
                            <% end %>
                        </div>

                        <div class="tab-pane fade" id="paneTwo1"><br>
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="thumbnail">
                                        <% if @course.instructor.image_url and @course.instructor.image_url != '' %>
                                            <img src="<%= @course.instructor.image_url %>" alt="Instructor Image">
                                        <% else %>
                                            <img src="/img/Instructor.png" alt="Instructor Default Image">
                                        <% end %>

                                        <div class="caption" align="center">
                                            <h3><%= @course.instructor.name %></h3>
                                            <% if @course.instructor.email and @course.instructor.email != '' %>
                                                <p>
                                                    <a type="button" class="btn btn-info" href="mailto:<%= @course.instructor.email %>">
                                                        <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
                                                        Send Message
                                                    </a>
                                                </p>
                                            <% end %>

                                            <% if @course.instructor.linkedin and @course.instructor.linkedin != '' %>
                                                <a href="<%= @course.instructor.linkedin %>" class="icons"><img src="/img/linkedin.png" width="24" height="24" alt=""/></a>
                                            <% end %>
                                        </div>
                                    </div>
                                </div>

                                <% if @course.instructor.bio and @course.instructor.bio != '' %>
                                    <div class="col-md-8">
                                        <div class="jumbotron">
                                            <h2>Biography</h2>
                                            <p><h5><%= @course.instructor.bio %></h5></p>
                                        </div>
                                    </div>
                                <% end %>
                            </div>
                        </div>

                        <div class="tab-pane fade" id="paneThree1">
                            <div class="col-md-8" id="tabDropDownOne1">
                                <% if @course.start %>
                                    <strong>Start Date</strong><br>
                                    <%= @course.start.strftime('%A, %d %B %Y') %>

                                    <hr>
                                <% end %>

                                <% if @course.place and @course.place != '' %>
                                    <strong>Place</strong><br>
                                    <%= @course.place %>

                                    <hr>
                                <% end %>

                                <% if @course.time and @course.time != '' %>
                                    <strong>Time</strong><br>
                                    <%= @course.time %>

                                    <hr>
                                <% end %>

                                <% if @course.duration and @course.duration != '' %>
                                    <strong>Duration</strong><br>
                                    <%= @course.duration %>
                                <% end %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <%= link_to 'Back', :back, class: 'btn btn-default' %>
        </div>
    </div>

    <footer class="text-center">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <p>Copyright © IEEE AlexSB | Software Development Committee</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script type="text/javascript" src="/js/jquery-1.11.2.min.js"></script>
    <script type="text/javascript" src="/js/jquery-ui.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
</body>
</html>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
    <thead>
    <tr>
        <th>Name</th>
        <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @users.each do |user| %>
        <tr>
            <td><%= user.name %></td>
            <td><%= link_to 'Show', user %></td>
            <td><%= link_to 'Edit', edit_user_path(user) %></td>
            <td><%= link_to 'Destroy', user, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
    <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
    <strong>Name:</strong>
    <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/visitors/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>IEEE AlexSB | Courses System </title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="/css/bootstrap.css">
    <link href="https://fonts.googleapis.com/css?family=Francois+One" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <nav class="navbar navbar-default" style="min-height:auto">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active"></li>
                    <a class="navbar-brand" href="/"><img src="/img/logo.png" width="200px"></a>
                </ul>

                <%= form_tag(search_path, method: 'get', class: "navbar-form navbar-right", id: "search-form", enforce_utf8: false) do %>
                    <div class="form-group">
                        <%= text_field_tag :search, params[:search], {class: 'form-control', placeholder: 'Search Courses'} %>
                    </div>
                    <button type="submit" class="btn btn-default">
                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span> Search
                    </button>

                    <a type="button" class="btn btn-success" href="/admin/login">
                        <% if user_signed_in? %>
                            Admin Panel
                        <% else %>
                            Login
                        <% end %>
                    </a>
                <% end %>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <div id="carousel2" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carousel2" data-slide-to="0" class="active"></li>
            <li data-target="#carousel2" data-slide-to="1"></li>
            <li data-target="#carousel2" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
            <div class="item active"><img src="/img/1.png" alt="First slide image" class="center-block">
                <div class="carousel-caption">
                    <h1>Register NOW</h1>
                    <p>Choose from courses in all fields</p>
                </div>
            </div>
            <div class="item"><img src="/img/3.gif" alt="Second slide image" class="center-block">
                <div class="carousel-caption">
                    <h2>Choose Yours</h2>
                </div>
            </div>
            <div class="item"><img src="/img/2.png" alt="Third slide image" class="center-block">
                <div class="carousel-caption">
                    <h1>Get Certified</h1>
                </div>
            </div>
        </div>
        <a class="left carousel-control" href="#carousel2" role="button" data-slide="prev"><span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span><span class="sr-only">Previous</span></a><a class="right carousel-control" href="#carousel2" role="button" data-slide="next"><span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span><span class="sr-only">Next</span></a>
    </div>
    <div class="container">
        <div class="row"></div>
    </div>

    <h1 class="text-center" id="font">MID YEAR COURSES</h1>

    <div class="btn-group-horizontal text-center">
        <%= link_to 'All Courses', root_path, class: 'btn btn-default' %>
        <% @categories.each do |category| %>
            <%= link_to category.name, root_path(:category_id => category.id), class: 'btn btn-default' %>
        <% end %>
    </div>

    <p></p>

    <% unless @courses.empty? %>
        <div id="tabContent1" class="tab-content" style="background: url(/img/IMG_0108.jpg);">
            <p>&nbsp;</p>
            <div class="container">
                <div class="row text-center">
                    <% @courses.each do |course| %>
                        <div class="col-xs-12 col-sm-6 col-md-4">
                            <div class="thumbnail">

                                <% if course.image_url and course.image_url != '' %>
                                    <img src="<%= course.image_url %>" alt="Course Image" class="img-responsive">
                                <% else %>
                                    <img src="/img/course.png" alt="Thumbnail Image 1" class="img-responsive">
                                <% end %>

                                <div class="caption">
                                    <h3><%= course.name %></h3>
                                    <p>
                                        <% if course.description and course.description != '' %>
                                            <%= course.description[0, 49] %>...
                                        <% end %>
                                    </p>
                                    <p>
                                        <a href="/courses/<%= course.id %>" class="btn btn-primary" role="button">
                                            <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                                            More Info
                                        </a>
                                    </p>
                                </div>
                            </div>
                        </div>
                    <% end %>
                </div>

                <nav class="text-center">
                    <!-- Add class .pagination-lg for larger blocks or .pagination-sm for smaller blocks-->
                    <span class="pagination">
                        <%= will_paginate @courses, renderer: BootstrapPagination::Rails %>
                    </span>
                </nav>
            </div>
        </div>
    <% else %>
        <div class="row">
            <div class="col-xs-12 text-center">
                <h1>No results</h1>
            </div>
        </div>
    <% end %>

    <footer class="text-center">
        <div><img src="/img/4.png" class="img-responsive" alt="Placeholder image"></div>
    </footer>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script type="text/javascript" src="/js/jquery-1.11.2.min.js"></script>
    <script type="text/javascript" src="/js/jquery-ui.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
</body>
</html>

app/views/visitors/search.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>IEEE AlexSB | Courses System </title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="/css/bootstrap.css">
    <link href="https://fonts.googleapis.com/css?family=Francois+One" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <nav class="navbar navbar-default" style="min-height:auto">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active"></li>
                    <a class="navbar-brand" href="/"><img src="/img/logo.png" width="200px"></a>
                </ul>

                <%= form_tag(search_path, method: 'get', class: "navbar-form navbar-right", id: "search-form", enforce_utf8: false) do %>
                    <div class="form-group">
                        <%= text_field_tag :search, params[:search], {class: 'form-control', placeholder: 'Search Courses'} %>
                    </div>
                    <button type="submit" class="btn btn-default">
                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span> Search
                    </button>

                    <a type="button" class="btn btn-success" href="/admin/login">
                        <% if user_signed_in? %>
                            Admin Panel
                        <% else %>
                            Login
                        <% end %>
                    </a>
                <% end %>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <h2 class="text-center">
        <!--"Searched Text Here or No Result Found"-->
        <% unless @courses and @courses.empty? %>
            Showing Results For "<%= @search_text %>"
        <% else %>
            No Results Found For "<%= @search_text %>"
        <% end %>
    </h2>
    <hr>

    <% unless @courses and @courses.empty? %>
        <div class="container">
            <div class="row text-center">
                <% @courses.each do |course| %>
                    <div class="col-xs-12 col-sm-6 col-md-4">
                        <div class="thumbnail">
                            <% if course.image_url and course.image_url != '' %>
                                <img src="<%= course.image_url %>" alt="Course Image" class="img-responsive">
                            <% else %>
                                <img src="/img/course.png" alt="Thumbnail Image 1" class="img-responsive">
                            <% end %>

                            <div class="caption">
                                <h3><%= course.name %></h3>
                                <p>
                                    <% if course.description and course.description != '' %>
                                        <%= course.description[0, 49] %>...
                                    <% end %>
                                </p>
                                <p>
                                    <a href="/courses/<%= course.id %>" class="btn btn-primary" role="button">
                                        <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                                        More Info
                                    </a>
                                </p>
                            </div>
                        </div>
                    </div>
                <% end %>
            </div>

            <nav class="text-center">
                <!-- Add class .pagination-lg for larger blocks or .pagination-sm for smaller blocks-->
                <span class="pagination">
                    <%= will_paginate @courses, renderer: BootstrapPagination::Rails %>
                </span>
            </nav>
        </div>
    <% end %>

    <footer class="text-center">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <p>Copyright © IEEE AlexSB | Software Development Committee</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script type="text/javascript" src="/js/jquery-1.11.2.min.js"></script>
    <script type="text/javascript" src="/js/jquery-ui.min.js"></script>
     <!--Include all compiled plugins (below), or include individual files as needed -->
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
</body>
</html>